Skullboard
compsci-adl/duckbot pull request #14
Opened 2024-07-08 00:17 UTC by phoenixpereira

### Description
Similar to the [Starboard Discord bot](https://discord.com/application-directory/655390915325591629), but instead works when people react with skull emojis.

### Changes Made
- Posts to skullboard if a message receives enough reactions

### Related Issues
Fixes #4 

### Additional Notes
N/A

2024-07-22 12:41 UTC, rayokamoto requested changes

2024-07-22 12:41 UTC, rayokamoto commented on .example.env
> +REQUIRED_REACTIONS=5
```suggestion
REQUIRED_REACTIONS=5

```

2024-07-22 12:41 UTC, rayokamoto commented on .github/workflows/production.yml
Are the env variables required for creating the Docker image? For the website it is required since Next.js wants to use them during builds, but I don't think it's necessary for the Discord bot. I'm pretty sure it would grab the env variables during runtime. I could be wrong though.

2024-07-22 12:41 UTC, rayokamoto commented on src/commands/skullboard.py
> +REQUIRED_REACTIONS = int(os.getenv("REQUIRED_REACTIONS"))
I think this can just be put into the `SkullboardManager` constructor.

2024-07-22 12:41 UTC, rayokamoto commented on src/commands/skullboard.py
For commenting functions, I suggest using multiline strings to create doc comments, rather than single line comments using `#`. See: https://peps.python.org/pep-0257/#multi-line-docstrings

2024-07-22 12:41 UTC, rayokamoto commented on src/commands/skullboard.py
> +            colour=Color.from_rgb(204, 214, 221),
We should store this color as a constant in a file somewhere

2024-07-22 12:41 UTC, rayokamoto commented on src/commands/skullboard.py
> +            ),
This is a bit unreadable so it might be preferable to extract it out into another variable.

2024-07-22 13:06 UTC, rayokamoto commented on .github/workflows/production.yml
Given the env variables are loaded from a local file anyway, do you think it's safe to just remove it from the workflow file?

2024-07-22 23:41 UTC, phoenixpereira commented on .github/workflows/production.yml
Yeah that should be fine.

2024-07-23 03:24 UTC, rayokamoto requested changes

2024-07-23 03:24 UTC, rayokamoto commented on src/commands/skullboard.py
> +from constants.colours import LIGHT_GREY
```suggestion
import os
import requests
import re

from discord import Embed, Client
from dotenv import load_dotenv

from constants.colours import LIGHT_GREY
```

I suggest breaking imports up into clear blocks of standard, third party, and project-specific imports - as suggested in [PEP 8](https://peps.python.org/pep-0008/#imports).

2024-07-23 03:24 UTC, rayokamoto commented on src/main.py
>  from dotenv import load_dotenv
Same comment as `skullboard.py`

2024-07-23 05:39 UTC, rayokamoto approved these changes

2024-07-23 05:46 UTC, jsun969 approved these changes
Awesome!

2024-07-23 05:58 UTC, merged