fix: Datetime rollover on 00:00
compsci-adl/duckbot pull request #44
Opened 2024-08-16 10:53 UTC by CrageJ

### Description
Fixed bug where the calculated day wouldn't roll over on 00:00
Added timestamp to logger

2024-08-16 11:56 UTC, rayokamoto approved these changes

2024-08-16 12:10 UTC, phoenixpereira requested changes

2024-08-16 12:10 UTC, phoenixpereira commented on src/commands/skullboard.py
> +from discord import (
Remove `Member` and `Message` as they aren't used.

2024-08-16 12:10 UTC, phoenixpereira commented on src/models/database.py
> +
Remove as it seems to be unused.

2024-08-16 12:10 UTC, phoenixpereira commented on src/utils/time.py
> +import pytz
Remove the duplicated imports and remove `timezone` and `timedelta` as they aren't used.

2024-08-16 12:10 UTC, phoenixpereira commented on src/utils/time.py
> +    """Generates a string representing the timestamp, in Australian time"""
Comment should say ACST or Adelaide time rather than Australian time.

2024-08-17 01:08 UTC, phoenixpereira approved these changes

2024-08-17 01:08 UTC, merged