Added more commands, plotting histogram data.
compsci-adl/duckbot pull request #47
Opened 2024-08-17 02:56 UTC by CrageJ

2024-08-17 04:02 UTC, rayokamoto requested changes

2024-08-17 04:02 UTC, rayokamoto commented on src/commands/skullboard.py
> +            )  # top percentile of skull reactions
Put the comments in the line above the statement to prevent wrapping like this when formatted by Black

2024-08-17 04:02 UTC, rayokamoto commented on src/commands/skullboard.py
Remember to order imports according to PEP 8.

Also for the logging (`logging.exception(...)`) the messages should be a bit more descriptive

2024-08-17 09:35 UTC, CrageJ commented
let me add the exception logging and we should be good here

2024-08-17 10:04 UTC, CrageJ commented on src/commands/skullboard.py
Logging now includes:
- Function
- Arguments
- Caller
- Timestamp
- Stacktrace

2024-08-19 03:07 UTC, rayokamoto requested changes
Small changes needed, otherwise good to go

2024-08-19 03:07 UTC, rayokamoto commented on src/commands/skullboard.py
> +from discord.utils import MISSING
```suggestion
from collections import Counter
from functools import wraps
from io import BytesIO
from typing import Callable, Awaitable

from discord import (
    AllowedMentions,
    Client,
    Embed,
    File,
    Interaction,
    Member,
    app_commands,
)
from discord.errors import NotFound
from discord.utils import MISSING
import requests
```

2024-08-19 03:07 UTC, rayokamoto commented on src/commands/skullboard.py
> +                    raise  # Re-raise other NotFound errors
```suggestion
                IGNORE_404_API_BUG_ERROR_CODE = 10062
                if e.code != IGNORE_404_API_BUG_ERROR_CODE:  # Supress API bug error
                    raise  # Re-raise other NotFound errors
```

2024-08-19 03:07 UTC, rayokamoto commented on src/commands/skullboard.py
> +        )  # percentile of posts meeting or exceeding threshold
Put the respective comments above the statements to prevent Black from wrapping statements like this

2024-08-19 03:33 UTC, rayokamoto approved these changes

2024-08-19 03:37 UTC, phoenixpereira approved these changes

2024-08-19 03:38 UTC, merged