fix: properly calculating time difference
compsci-adl/duckbot pull request #53
Opened 2024-09-02 04:59 UTC by ChristianDianos

### Description
When FNG would be a day away, or two days away, the time difference calculated would be 0.0. This pull request aims to fix that.

### Changes Made
Altered logic for calculating time difference and checking time difference

### Related Issues
N/A

### Additional Notes
N/A

2024-09-02 06:02 UTC, rayokamoto approved these changes

2024-09-02 06:36 UTC, phoenixpereira requested changes

2024-09-02 06:36 UTC, phoenixpereira commented on src/commands/faq.py
This should fix the 0.0 hours bug, but you should use `pytz` to set the timezone to Adelaide, otherwise the time will be 9.5 hours off. See `utils/time.py` for an example.

2024-09-02 07:37 UTC, rayokamoto commented on src/commands/faq.py
Yeah, this. I forgot about the timetable issue

2024-09-22 13:06 UTC, phoenixpereira requested changes

2024-09-23 10:28 UTC, rayokamoto commented
Any updates on this?

2024-09-24 04:49 UTC, phoenixpereira approved these changes

2024-09-24 04:50 UTC, merged